-- 1) serveur (nom_noeud + environnement extrait du suffixe)
INSERT INTO serveur (nom_noeud, environnement) VALUES
    ('NODE-10-DEV', 'DEV'),
    ('NODE-11-PROD', 'PROD'),
    ('NODE-14-PROD', 'PROD'),
    ('NODE-15-QA', 'QA'),
    ('NODE-16-DEV', 'DEV'),
    ('NODE-17-DEV', 'DEV'),
    ('NODE-20-DEV', 'DEV'),
    ('NODE-20-PROD', 'PROD'),
    ('NODE-24-DEV', 'DEV'),
    ('NODE-25-QA', 'QA'),
    ('NODE-26-QA', 'QA'),
    ('NODE-27-DEV', 'DEV'),
    ('NODE-27-QA', 'QA'),
    ('NODE-28-QA', 'QA'),
    ('NODE-32-QA', 'QA'),
    ('NODE-33-QA', 'QA'),
    ('NODE-35-DEV', 'DEV'),
    ('NODE-36-QA', 'QA'),
    ('NODE-37-QA', 'QA'),
    ('NODE-39-PROD', 'PROD'),
    ('NODE-40-QA', 'QA'),
    ('NODE-42-QA', 'QA'),
    ('NODE-46-QA', 'QA'),
    ('NODE-48-DEV', 'DEV'),
    ('NODE-48-PROD', 'PROD'),
    ('NODE-49-DEV', 'DEV'),
    ('NODE-49-PROD', 'PROD'),
    ('NODE-50-QA', 'QA'),
    ('NODE-52-PROD', 'PROD'),
    ('NODE-54-DEV', 'DEV'),
    ('NODE-57-QA', 'QA'),
    ('NODE-60-PROD', 'PROD'),
    ('NODE-61-PROD', 'PROD'),
    ('NODE-64-PROD', 'PROD'),
    ('NODE-65-PROD', 'PROD'),
    ('NODE-67-DEV', 'DEV'),
    ('NODE-68-DEV', 'DEV'),
    ('NODE-72-DEV', 'DEV'),
    ('NODE-73-PROD', 'PROD'),
    ('NODE-74-DEV', 'DEV'),
    ('NODE-74-QA', 'QA'),
    ('NODE-75-PROD', 'PROD'),
    ('NODE-77-DEV', 'DEV'),
    ('NODE-77-PROD', 'PROD'),
    ('NODE-77-QA', 'QA'),
    ('NODE-78-DEV', 'DEV'),
    ('NODE-78-QA', 'QA'),
    ('NODE-80-QA', 'QA'),
    ('NODE-81-PROD', 'PROD'),
    ('NODE-81-QA', 'QA'),
    ('NODE-83-QA', 'QA'),
    ('NODE-85-QA', 'QA'),
    ('NODE-87-PROD', 'PROD'),
    ('NODE-87-QA', 'QA'),
    ('NODE-89-QA', 'QA'),
    ('NODE-90-QA', 'QA'),
    ('NODE-91-QA', 'QA'),
    ('NODE-92-PROD', 'PROD'),
    ('NODE-94-DEV', 'DEV'),
    ('NODE-94-PROD', 'PROD');

-- 2) module_sap
INSERT INTO module_sap (nom_module) VALUES
    ('SAP Ariba'),
    ('SAP BW/4HANA'),
    ('SAP CRM'),
    ('SAP Concur'),
    ('SAP EWM'),
    ('SAP FI-CO'),
    ('SAP Fieldglass'),
    ('SAP Fiori'),
    ('SAP GRC'),
    ('SAP HANA'),
    ('SAP HCM'),
    ('SAP IBP'),
    ('SAP MDG'),
    ('SAP MM'),
    ('SAP PLM'),
    ('SAP PM'),
    ('SAP PP'),
    ('SAP PS'),
    ('SAP QM'),
    ('SAP SCM'),
    ('SAP SD'),
    ('SAP SuccessFactors');

-- 3) type_incident
INSERT INTO type_incident (libelle_type) VALUES
    ('Accès refusé'),
    ('Badge non reconnu'),
    ('Boîte pleine (quota dépassé)'),
    ('Coupure de connexion'),
    ('Double réservation détectée'),
    ('Email classé en spam à tort'),
    ('Erreur d''affichage des données'),
    ('File d''attente bloquée'),
    ('Justificatif non pris en compte'),
    ('Lenteur à la connexion'),
    ('Mise à jour bloquée'),
    ('Mot de passe expiré non renouvelé'),
    ('Notification non reçue'),
    ('Page qui ne charge pas'),
    ('Plantage aléatoire de l''application'),
    ('Réseau invité inaccessible'),
    ('Synchronisation en échec'),
    ('Ticket bloqué en statut ''En cours'''),
    ('Écart entre données réelles et affichées');

-- 4) processus_metier (nom_processus uniquement, numero_workflow deplace vers service_sap)
INSERT INTO processus_metier (nom_processus) VALUES
    ('Asset Tracking'),
    ('Budget Allocation'),
    ('Equipment Maintenance'),
    ('Expense Reporting'),
    ('Financial Dashboards'),
    ('Fleet Logistics'),
    ('Inventory Audits'),
    ('Invoice Processing'),
    ('Lead Generation'),
    ('Master Data Governance'),
    ('Onboarding'),
    ('Order Routing'),
    ('Payroll Management'),
    ('Production Scheduling'),
    ('Quality Checks'),
    ('Risk Assessment'),
    ('Supplier Contracting'),
    ('Talent Acquisition');
