-- Import ticket_helpdesk (40 lignes)
-- NB: quand un nom d'application existe en double dans le catalogue ServiceNow (ex: "Intranet Entreprise"),
-- on prend la premiere correspondance (LIMIT 1) faute de precision dans la source HelpDesk
INSERT INTO ticket_helpdesk (description, priorite, statut, date_creation, id_application, id_departement, id_type_incident)
SELECT 'Erreur d''affichage des données signalé par un utilisateur sur Intranet Entreprise.', 'Moyenne', 'Résolu', '2025-08-26'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Intranet Entreprise' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Sécurité'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Erreur d''affichage des données')
UNION ALL
SELECT 'Justificatif non pris en compte signalé par un utilisateur sur Intranet Entreprise.', 'Critique', 'Résolu', '2026-06-29'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Intranet Entreprise' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'RH'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Justificatif non pris en compte')
UNION ALL
SELECT 'Mot de passe expiré non renouvelé signalé par un utilisateur sur Outil de Signature Électronique.', 'Moyenne', 'Résolu', '2025-09-05'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Signature Électronique' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Support'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Mot de passe expiré non renouvelé')
UNION ALL
SELECT 'Page qui ne charge pas signalé par un utilisateur sur Plateforme de Formation en Ligne.', 'Haute', 'Résolu', '2025-11-05'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme de Formation en Ligne' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Sécurité'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Page qui ne charge pas')
UNION ALL
SELECT 'File d''attente bloquée signalé par un utilisateur sur Plateforme de Formation en Ligne.', 'Moyenne', 'En cours', '2025-08-15'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme de Formation en Ligne' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Commercial'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'File d''attente bloquée')
UNION ALL
SELECT 'Double réservation détectée signalé par un utilisateur sur CRM Commercial.', 'Moyenne', 'Résolu', '2026-03-02'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'CRM Commercial' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Sécurité'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Double réservation détectée')
UNION ALL
SELECT 'Justificatif non pris en compte signalé par un utilisateur sur Outil de Gestion des Stocks.', 'Haute', 'En cours', '2025-10-02'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Gestion des Stocks' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'IT'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Justificatif non pris en compte')
UNION ALL
SELECT 'Notification non reçue signalé par un utilisateur sur Système de Paie Externalisé.', 'Haute', 'Résolu', '2026-02-05'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Système de Paie Externalisé' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Commercial'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Notification non reçue')
UNION ALL
SELECT 'Coupure de connexion signalé par un utilisateur sur Outil de Gestion des Accès.', 'Critique', 'Résolu', '2026-04-19'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Gestion des Accès' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Sécurité'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Coupure de connexion')
UNION ALL
SELECT 'Synchronisation en échec signalé par un utilisateur sur Système de Paie Externalisé.', 'Haute', 'En attente', '2025-08-29'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Système de Paie Externalisé' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Commercial'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Synchronisation en échec')
UNION ALL
SELECT 'Mise à jour bloquée signalé par un utilisateur sur Plateforme Marketing Automation.', 'Haute', 'Résolu', '2026-01-07'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme Marketing Automation' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Opérations'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Mise à jour bloquée')
UNION ALL
SELECT 'Réseau invité inaccessible signalé par un utilisateur sur Outil de Ticketing IT.', 'Basse', 'Résolu', '2026-04-28'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Ticketing IT' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Juridique'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Réseau invité inaccessible')
UNION ALL
SELECT 'Synchronisation en échec signalé par un utilisateur sur CRM Commercial.', 'Moyenne', 'En cours', '2026-07-20'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'CRM Commercial' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Sécurité'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Synchronisation en échec')
UNION ALL
SELECT 'Coupure de connexion signalé par un utilisateur sur Intranet Entreprise.', 'Critique', 'En attente', '2026-06-13'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Intranet Entreprise' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Opérations'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Coupure de connexion')
UNION ALL
SELECT 'File d''attente bloquée signalé par un utilisateur sur Système de Paie Externalisé.', 'Basse', 'En attente', '2026-01-22'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Système de Paie Externalisé' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'IT'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'File d''attente bloquée')
UNION ALL
SELECT 'Mot de passe expiré non renouvelé signalé par un utilisateur sur Système de Paie Externalisé.', 'Basse', 'Résolu', '2026-06-03'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Système de Paie Externalisé' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Support'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Mot de passe expiré non renouvelé')
UNION ALL
SELECT 'Accès refusé signalé par un utilisateur sur Plateforme Marketing Automation.', 'Basse', 'Résolu', '2026-04-14'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme Marketing Automation' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Juridique'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Accès refusé')
UNION ALL
SELECT 'Accès refusé signalé par un utilisateur sur CRM Commercial.', 'Basse', 'Résolu', '2026-01-01'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'CRM Commercial' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Direction'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Accès refusé')
UNION ALL
SELECT 'Plantage aléatoire de l''application signalé par un utilisateur sur CRM Commercial.', 'Moyenne', 'Résolu', '2026-01-20'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'CRM Commercial' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Commercial'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Plantage aléatoire de l''application')
UNION ALL
SELECT 'File d''attente bloquée signalé par un utilisateur sur Plateforme de Formation en Ligne.', 'Basse', 'En attente', '2026-06-03'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme de Formation en Ligne' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Direction'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'File d''attente bloquée')
UNION ALL
SELECT 'Badge non reconnu signalé par un utilisateur sur Outil de Facturation.', 'Basse', 'Résolu', '2026-07-01'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Facturation' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'IT'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Badge non reconnu')
UNION ALL
SELECT 'Justificatif non pris en compte signalé par un utilisateur sur Portail RH Interne.', 'Moyenne', 'En attente', '2026-06-03'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Portail RH Interne' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'IT'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Justificatif non pris en compte')
UNION ALL
SELECT 'Notification non reçue signalé par un utilisateur sur Intranet Entreprise.', 'Basse', 'En attente', '2026-02-14'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Intranet Entreprise' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Juridique'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Notification non reçue')
UNION ALL
SELECT 'Synchronisation en échec signalé par un utilisateur sur Outil de Ticketing IT.', 'Critique', 'En attente', '2026-07-10'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Ticketing IT' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Sécurité'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Synchronisation en échec')
UNION ALL
SELECT 'Double réservation détectée signalé par un utilisateur sur Plateforme de Formation en Ligne.', 'Critique', 'Résolu', '2026-01-13'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme de Formation en Ligne' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Direction'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Double réservation détectée')
UNION ALL
SELECT 'Page qui ne charge pas signalé par un utilisateur sur Plateforme Marketing Automation.', 'Critique', 'Résolu', '2025-12-06'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme Marketing Automation' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Marketing'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Page qui ne charge pas')
UNION ALL
SELECT 'Réseau invité inaccessible signalé par un utilisateur sur Outil de Signature Électronique.', 'Basse', 'Résolu', '2025-08-30'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Signature Électronique' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Juridique'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Réseau invité inaccessible')
UNION ALL
SELECT 'Notification non reçue signalé par un utilisateur sur Outil de Gestion des Accès.', 'Basse', 'En attente', '2025-10-20'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Gestion des Accès' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Support'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Notification non reçue')
UNION ALL
SELECT 'Justificatif non pris en compte signalé par un utilisateur sur Plateforme Marketing Automation.', 'Moyenne', 'Résolu', '2026-02-16'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme Marketing Automation' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Facilities'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Justificatif non pris en compte')
UNION ALL
SELECT 'Mot de passe expiré non renouvelé signalé par un utilisateur sur Intranet Entreprise.', 'Moyenne', 'Résolu', '2025-10-13'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Intranet Entreprise' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'IT'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Mot de passe expiré non renouvelé')
UNION ALL
SELECT 'Écart entre données réelles et affichées signalé par un utilisateur sur Outil de Gestion des Stocks.', 'Moyenne', 'Résolu', '2025-08-12'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Gestion des Stocks' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'RH'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Écart entre données réelles et affichées')
UNION ALL
SELECT 'Page qui ne charge pas signalé par un utilisateur sur Outil de Gestion des Accès.', 'Moyenne', 'En attente', '2025-09-08'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Gestion des Accès' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Direction'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Page qui ne charge pas')
UNION ALL
SELECT 'Justificatif non pris en compte signalé par un utilisateur sur Outil de Gestion des Accès.', 'Critique', 'Résolu', '2026-04-20'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Gestion des Accès' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Juridique'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Justificatif non pris en compte')
UNION ALL
SELECT 'Ticket bloqué en statut ''En cours'' signalé par un utilisateur sur CRM Commercial.', 'Critique', 'Résolu', '2025-11-03'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'CRM Commercial' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Sécurité'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Ticket bloqué en statut ''En cours''')
UNION ALL
SELECT 'Boîte pleine (quota dépassé) signalé par un utilisateur sur Plateforme Marketing Automation.', 'Basse', 'Résolu', '2025-10-23'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme Marketing Automation' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Juridique'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Boîte pleine (quota dépassé)')
UNION ALL
SELECT 'Coupure de connexion signalé par un utilisateur sur Outil de Gestion des Stocks.', 'Basse', 'Résolu', '2026-04-30'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Outil de Gestion des Stocks' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Support'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Coupure de connexion')
UNION ALL
SELECT 'Page qui ne charge pas signalé par un utilisateur sur Portail RH Interne.', 'Critique', 'Résolu', '2026-04-30'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Portail RH Interne' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Direction'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Page qui ne charge pas')
UNION ALL
SELECT 'Accès refusé signalé par un utilisateur sur Plateforme Marketing Automation.', 'Critique', 'Résolu', '2025-12-20'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme Marketing Automation' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Marketing'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Accès refusé')
UNION ALL
SELECT 'Email classé en spam à tort signalé par un utilisateur sur Intranet Entreprise.', 'Basse', 'Résolu', '2025-10-12'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Intranet Entreprise' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'Direction'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Email classé en spam à tort')
UNION ALL
SELECT 'Lenteur à la connexion signalé par un utilisateur sur Plateforme Marketing Automation.', 'Moyenne', 'Résolu', '2026-03-26'::DATE, (SELECT id_application FROM application WHERE nom_canonique = 'Plateforme Marketing Automation' LIMIT 1), (SELECT id_departement FROM departement WHERE nom_departement = 'RH'), (SELECT id_type_incident FROM type_incident WHERE libelle_type = 'Lenteur à la connexion');
